# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_coordinateX = QtWidgets.QLabel(self.centralwidget)
        self.label_coordinateX.setGeometry(QtCore.QRect(30, 30, 131, 61))
        self.label_coordinateX.setStyleSheet("font: italic 14pt \"Cambria\";")
        self.label_coordinateX.setObjectName("label_coordinateX")
        self.label_coordinateY = QtWidgets.QLabel(self.centralwidget)
        self.label_coordinateY.setGeometry(QtCore.QRect(30, 90, 131, 61))
        self.label_coordinateY.setStyleSheet("font: italic 14pt \"Cambria\";")
        self.label_coordinateY.setObjectName("label_coordinateY")
        self.label_coordinateZ = QtWidgets.QLabel(self.centralwidget)
        self.label_coordinateZ.setGeometry(QtCore.QRect(30, 150, 131, 61))
        self.label_coordinateZ.setStyleSheet("font: italic 14pt \"Cambria\";")
        self.label_coordinateZ.setObjectName("label_coordinateZ")
        self.sbox_coordinateZ = QtWidgets.QSpinBox(self.centralwidget)
        self.sbox_coordinateZ.setGeometry(QtCore.QRect(170, 170, 591, 21))
        self.sbox_coordinateZ.setMaximum(17)
        self.sbox_coordinateZ.setObjectName("sbox_coordinateZ")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(110, 260, 600, 381))
        self.picture.setMaximumSize(QtCore.QSize(600, 450))
        self.picture.setObjectName("picture")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 660, 801, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 220, 121, 31))
        self.pushButton.setStyleSheet("font: 14pt \"Cambria\";")
        self.pushButton.setObjectName("pushButton")
        self.line_coordinateX = QtWidgets.QLineEdit(self.centralwidget)
        self.line_coordinateX.setGeometry(QtCore.QRect(170, 50, 591, 22))
        self.line_coordinateX.setObjectName("line_coordinateX")
        self.line_coordinateY = QtWidgets.QLineEdit(self.centralwidget)
        self.line_coordinateY.setGeometry(QtCore.QRect(170, 110, 591, 22))
        self.line_coordinateY.setObjectName("line_coordinateY")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_coordinateX.setText(_translate("MainWindow", "X coordinate:"))
        self.label_coordinateY.setText(_translate("MainWindow", "Y coordinate:"))
        self.label_coordinateZ.setText(_translate("MainWindow", "Z (scale) < 17"))
        self.picture.setText(_translate("MainWindow", " "))
        self.pushButton.setText(_translate("MainWindow", "\'OK\'"))
